### ISSUE TITLE
How can I contribute?

### ISSUE THREAD

**Issue by filib** [txus/kleisli#10]
I'd really like to contribute to the project but not sure where to begin. I authored another gem to add `Maybe` to the Ruby ecosystem and focussed on writing tests to prove it adhered to various laws, e.g. https://github.com/filib/ribimaybe/blob/master/spec/applicative_functor_spec.rb. Is this something you feel would be a valuable addition to the to `kleisli`?

**Comment by filib** [comment]
Did you folks have any thoughts on this? I don't mind if the answer is, "you can't, sod off."

**Comment by parkr** [comment]
I can't speak for @txus and @rylev, but I think any feature you think is missing or can be improved (performance, perhaps) is a great place to start. Looks pretty full-featured to me.

**Comment by txus** [comment]
@filib sorry for the delay! Testing laws seems like a great start to me. A thing that I haven't had any time to look at either is the Parser monad, I'd love to have that in kleisli. :) I'm looking forward to your contributions, much appreciated! :D

**Comment by filib** [comment]
:+1:
