### ISSUE TITLE
Gem release

### ISSUE THREAD

**Issue by abevoelker** [txus/kleisli#16]
I've got a gem that depends on `kleisli` that could benefit from the `Try#to_either` change. Would it be possible to get a new gem version released that contains that change?

**Comment by abevoelker** [comment]
<sup>Quiet bump</sup>

**Comment by abevoelker** [comment]
<sup><sup>Still hoping</sup></sup>

**Comment by parkr** [comment]
@txus where you at

**Comment by txus** [comment]
0.2.7 fresh off the press on Rubygems -- sorry for the wait! @abevoelker

**Comment by abevoelker** [comment]
Thank you!! :metal: And sorry for the pestering.
