### ISSUE TITLE
Shouldn't Maybe(None) be None?

### ISSUE THREAD

**Issue by davidpelaez** [txus/kleisli#18]
I don't know if there's some obvious mistake I'm missing, but I feel that `Maybe(nil) == Maybe(None)` but that's not the case. Is this on purpose and I'm missing the reason? Thanks!

This is related to my question here: https://github.com/dryrb/dry-types/issues/35

**Comment by txus** [comment]
@davidpelaez: `Maybe(x)` is a convenience constructor useful when dealing with uncertain user input for example, to avoid repeatedly typing `x.nil ? Maybe::None : Maybe::Some(x)`.
On the other hand, calling this convenience function with a `None` evaluates to `Some(None)`, which is of type `Maybe (Maybe a)`, which is a legitimate type on its own. Automatically `join`ing `Some(None)` to `None` would implicitly change its type from `Maybe (Maybe a)` to `Maybe a`, which is not ideal.
I understand that it is strange when you end up with a `Some(None)`, but you shouldn't end up with one if you know that the value `x` you're dealing with is a `Maybe a`, not an `a`.
I'm not sure if I explained myself well, but I'm happy to discuss further :) Leaving the issue open to that regard for now.

**Comment by davidpelaez** [comment]
Thanks for the explanation @txus I understand now that `Maybe (Maybe a)` "is a legitimate type on its own". It's just the lack of experience that made it weird. But I get the point. I would then have to verify instead of wrapping a potential `None` inside another Maybe to avoid the issue then. 

Thank you for releasing Kleisli, some tools using it like Call Sheet have changed the way I think about code so much. It's like discovering a rich dialect inside Ruby, refreshing and enriching. :+1:
