### ISSUE TITLE
Optional bind variable

### ISSUE THREAD

**Issue by gottfrois** [txus/kleisli#3]
I was playing around with your gem and wanted to know if it's possible to not set a variable to hold the binded value when using the `Try` monad?

Here is a piece of code to illustrate:

``` ruby
require 'kleisli'

class A

  def call
    Try { foo } >-> _ { Try { bar } }
  end

  def foo
    if rand(3) == 1
      raise 'foo raised'
    else
      true
    end
  end

  def bar
    if rand(3) == 1
      raise 'bar raised'
    else
      true
    end
  end

end

r = A.new.call

puts r.value
puts r.exception
```

Since I don't use the value returned by the `foo` method, I used the `_` syntax. But I was wondering if there is a nicer way to "chain" the `foo` and `bar` method without the need to set the intermediate variables?

Also, is there a better way to chain those methods? Something that would look like this:

``` ruby
Try { foo } >-> Try { bar }
```

**Comment by beezee** [comment]
@gottfrois check out https://github.com/beezee/kleisli-run - it provides do-notation syntax that I think gets you what you are looking for in a concise manner.

**Comment by gottfrois** [comment]
Thanks man ! Sounds promising
